#!/usr/bin/python3
def raise_exception():
    value_1 = 1
    value_2 = 'Atnafu'
    result = value_1 // value_2
